### ISSUE TITLE
Implement view modes

### ISSUE THREAD

**Issue by Emerjoin** [Emerjoin/Hi-Framework#117]
# Feature description
View modes allows one view to have different presentations, each presentation on its own HTML file.
For example: student/register would have 3 files: _register.html, register.js **and** register-mini.html_.
The _register-mini.html_ will only be fetched and displayed only if the HTTP request contains a Get param named $=mini. 

# Affected behaviors
## View caching
View mode HTML content must be cached separately

**Comment by Romildo-Cumbe** [comment]
Dude.. The other file can't be **register-mini.html**, it has to be **register.mini.html** 

Separate it with dot's and not hyphens.
