### ISSUE TITLE
Hi framework based apps unable to run on root context

### ISSUE THREAD

**Issue by Edgencio** [Emerjoin/Hi-Framework#4]
I noticed that **apps do not run on root context**. I've been trying to execute a sample app on both glassfish and tomcat (tommee plume) servers, and i  think the problem extends to all other application servers!
I initially thought this problem only occurred in the first version of Hi, but I noticed that the problem persists even in the latest version...

**Comment by emjunior258** [comment]
Hi. @Edgencio, we will perform some tests and see if its really a framework problem and if so we will add it to a specific milestone and flag it as bug. In the meantime, you can run your app behind a reverse proxy and achieve a context-less URL scenario as you wish.

**Comment by emjunior258** [comment]
Fixed in Hi-Framework 1.4.0
